# Generated by Django 6.0 on 2025-12-12 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Programmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=100)),
                ('experience', models.DecimalField(decimal_places=2, max_digits=50)),
            ],
            options={
                'verbose_name': 'Programmer',
                'verbose_name_plural': 'Programmers',
            },
        ),
    ]
